---
- name: Check if dropbox is installed
  command: dpkg-query -W dropbox
  register: installed
  failed_when: installed.rc > 1
  changed_when: installed.rc == 1

- block:
  - name: Install dependencies
    apt: pkg={{ item }} state=installed update_cache=yes
    with_items:
      - python-gpgme
      - pyopenssl
    become: true

  - name: Set Ubuntu Download Link
    set_fact: dropbox_link={{ dropbox_link_ubuntu }}
    when: ansible_distribution in [ 'Ubuntu', 'Linuxmint' ]

  - name: Set Debian Download Link
    set_fact: dropbox_link={{ dropbox_link_debian }}
    when: ansible_distribution == 'Debian'

  ##########################################################33
  ##  WORKAROUND FOR CERT ERRORS WITH PYTHON < 2.7.9
  ##########################################################33
#  - name: Install wget
#    apt: pkg=wget state=installed
#
#  - name: Download dropbox deb (cert workaround)
#    command: wget -q -o /tmp/dropbox.deb {{ dropbox_link }}
#
#  - name: Install deb
#    apt: deb=/tmp/dropbox.deb
#    become: true
  ##########################################################33
  ##  END WORKAROUND
  ##########################################################33
  # Calls get_url which fails due to low python version
  # which can't resolve SNI thus breaking SSL
  # Workaround is to download specifically with: validate_certs=false
  # or use wget/curl which support SNI
  - name: Update python
    apt: pkg=python state=latest
    become: true

  - name: Install deb
    apt: deb={{ dropbox_link }}
    become: true

  when: installed|failed

# No longer working ;(
# - name: Install the deamon
#   shell: "dropbox start -i"
