---
- name: Check if dropbox is installed
  command: dpkg-query -W dropbox
  register: installed
  failed_when: installed.rc > 1
  changed_when: installed.rc == 1

- block:
  - name: Install dependencies
    apt: pkg={{ item }} state=installed update_cache=yes
    with_items:
      - python-gpgme
    become: true

  - name: Set Ubuntu Download Link
    set_fact: dropbox_link={{ dropbox_link_ubuntu }}
    when: ansible_distribution in [ 'Ubuntu', 'Linuxmint' ]

  - name: Set Debian Download Link
    set_fact: dropbox_link={{ dropbox_link_debian }}
    when: ansible_distribution == 'Debian'

  ############################################################
  ##  WORKAROUND FOR CERT ERRORS WITH PYTHON < 2.7.9
  ############################################################
  - name: Install wget (cert workaround)
    apt: pkg=wget state=installed

  - name: Download dropbox deb (cert workaround)
    command:  wget -q -O /tmp/dropbox.deb {{ dropbox_link }}
              creates=/tmp/dropbox.deb

  - name: Install deb (cert workaround)
    apt: deb=/tmp/dropbox.deb
    become: true
  ############################################################
  ##  END WORKAROUND
  ############################################################
  # Calls get_url which fails due to low python version
  # which can't resolve SNI thus breaking SSL
  # Workaround is to download specifically with: validate_certs=false
  # or use wget/curl which support SNI
#  - name: Install deb
#    apt: deb={{ dropbox_link }}
#    become: true

  when: installed|failed

  ############################################################
  ##  This used to launch the UI, doesn't appear to work now
  ############################################################
  # - name: Install the deamon
#   shell: "dropbox start -i"
